<?php
  // Define some configuration parameters
  define("DATABASE_NAME", "SHOPCART_wincomstore");
  define("BASKET_ID_LIFE", "7200");
  define("MAX_BUNDLES", 10);
  define("MAX_BUNDLE_ITEMS", 10);
  define("AD_LOC_ID", "1");

  // Define some checkout parameters
  define("USE_SHIPPING", 1);

  // Define the cacheing parameters
  define("USE_CACHEING", 1);

  // Define the PGP email parameters
  define("PGP_RCPT_PUBKEY_ID", "Rob Pinciuc <robp@wincom.net>");
?>
