<?php
  // Get some configuration constants and functions
  require("../inc/global_config.inc");
  require("../inc/config.inc");
  require("../inc/classes.inc");
  require("../inc/functions.inc");
  require("../inc/html.inc");

  // Connect to the SQL server and select the database
  $sock = db_connect();
  $config = new Config();

  if (!$step) {
    $new_start_date = date("Y-m-d");
    $new_start_time = "00:00:00";
    $new_end_date = $new_start_date;
    $new_end_time = "00:00:00";
  }

  if ($step) {
    $query = "SELECT * FROM discount_codes
              ORDER BY id";

    if (!$sql_result = mysql_query($query, $sock)) {
      echo mysql_error();
      html_exit();
    }

    for ($a = 0; $a < mysql_num_rows($sql_result); $a++) {
      $item = new DiscountCode(mysql_fetch_row($sql_result), 0);

      $description_var = $item->id . "-description";
      $start_date_var = $item->id . "-start_date";
      $start_time_var = $item->id . "-start_time";
      $end_date_var = $item->id . "-end_date";
      $end_time_var = $item->id . "-end_time";
      $units_var = $item->id . "-units";
      $code_id_var = $item->id . "-code_id";

      if (strlen($$description_var) && 
          strlen($$start_date_var) && strlen($$start_time_var) &&
          strlen($$end_date_var) && strlen($$end_time_var) &&
          strlen($$units_var) && strlen($$code_id_var)) {

        $start_date_array = explode("-", $$start_date_var);
        $start_time_array = explode(":", $$start_time_var);
        $end_date_array = explode("-", $$end_date_var);
        $end_time_array = explode(":", $$end_time_var);

        // I don't know why, but PHP won't let me use the arrays
        // in the mktime() call, so assign those elements to some
        // simple vars
        $s1 = $start_time_array[0];
        $s2 = $start_time_array[1];
        $s3 = $start_time_array[2];
        $s4 = $start_date_array[0];
        $s5 = $start_date_array[1];
        $s6 = $start_date_array[2];

        $e1 = $end_time_array[0];
        $e2 = $end_time_array[1];
        $e3 = $end_time_array[2];
        $e4 = $end_date_array[0];
        $e5 = $end_date_array[1];
        $e6 = $end_date_array[2];

        $start_timestamp = mktime($s1, $s2, $s3, $s5, $s6, $s4);
/*
             $start_time_array[0], $start_time_array[1], $start_time_array[2],
             $start_date_array[1], $start_time_array[2], $start_time_array[0]);
*/

        $end_timestamp = mktime($e1, $e2, $e3, $e5, $e6, $e4);
/*
             $end_time_array[0], $end_time_array[1], $end_time_array[2],
             $end_date_array[1], $end_time_array[2], $end_time_array[0]);
*/

        if ($start_timestamp <= $end_timestamp) {
          $item->description = $$description_var;
          $item->start_time = $start_timestamp;
          $item->end_time = $end_timestamp;
          $item->units = $$units_var;
          $item->code_id = $$code_id_var;

          $item->update();
        }
      }
    }
  }

  if ($step && $delete && is_array($delete)) {
    for ($a = 0; $a < count($delete); $a++) {
      $item = new DiscountCode(0, $delete[$a]);
      $item->delete();
    }
  }

  if ($step && strlen($new_description) && 
      strlen($new_start_date) && strlen($new_start_time) &&
      strlen($new_end_date) && strlen($new_end_time) &&
      strlen($new_units) && strlen($new_code_id)) {

    $newitem = new DiscountCode();

    $start_date_array = explode("-", $new_start_date);
    $start_time_array = explode(":", $new_start_time);
    $end_date_array = explode("-", $new_end_date);
    $end_time_array = explode(":", $new_end_time);

    // I don't know why, but PHP won't let me use the arrays
    // in the mktime() call, so assign those elements to some
    // simple vars
    $s1 = $start_time_array[0];
    $s2 = $start_time_array[1];
    $s3 = $start_time_array[2];
    $s4 = $start_date_array[0];
    $s5 = $start_date_array[1];
    $s6 = $start_date_array[2];

    $e1 = $end_time_array[0];
    $e2 = $end_time_array[1];
    $e3 = $end_time_array[2];
    $e4 = $end_date_array[0];
    $e5 = $end_date_array[1];
    $e6 = $end_date_array[2];

    $start_timestamp = mktime($s1, $s2, $s3, $s5, $s6, $s4);
/*
         $start_time_array[0], $start_time_array[1], $start_time_array[2],
         $start_date_array[1], $start_time_array[2], $start_time_array[0]);
*/

    $end_timestamp = mktime($e1, $e2, $e3, $e5, $e6, $e4);
/*
         $end_time_array[0], $end_time_array[1], $end_time_array[2],
         $end_date_array[1], $end_time_array[2], $end_time_array[0]);
*/

    if ($start_timestamp <= $end_timestamp) {
      $newitem->description = $new_description;
      $newitem->start_time = $start_timestamp;
      $newitem->end_time = $end_timestamp;
      $newitem->units = $new_units;
      $newitem->code_id = $new_code_id;

      $newitem->insert();

      $errmsg = "New code inserted.";
    }
    else {
      $errmsg = "End time before Start Time.";
    }
  }

  $query = "SELECT * FROM discount_codes
            ORDER BY id";

  if (!$sql_result = mysql_query($query, $sock)) {
    echo mysql_error();
    html_exit();
  }

  for ($a = 0; $a < mysql_num_rows($sql_result); $a++) {
    $item = new DiscountCode(mysql_fetch_row($sql_result), 0);
    $discountcodes[] = $item;
  }

  $query = "SELECT * FROM scale_codes
            ORDER BY id";

  if (!$sql_result = mysql_query($query, $sock)) {
    echo mysql_error();
    html_exit();
  }

  for ($a = 0; $a < mysql_num_rows($sql_result); $a++) {
    $item = new ScaleCode(mysql_fetch_row($sql_result), 0);
    $scalecodes[] = $item;
  }

  html_head();
?>

<a href="scalecodes.phtml"><font color=Green>Scale Codes</font></a> |
<b>Discount Codes</b> |
<a href="discassign.phtml"><font color=Green>Discount Assignments</font></a>

<hr noshade size=1>

<p>

<?php if ($errmsg) echo "<b>$errmsg</b><p>\n\n"; ?>

<form action="<?php echo $PHP_SELF ?>" method="post">
<input type=hidden name="step" value="1">


<table border=2 cellpadding=4 cellspacing=0 width=400>
<tr>
<td colspan=6><?php echo FONT1 ?>
<br>
<blockquote>
Create discount codes by assigning starting and ending times, a discount unit, and a scale code. Then, assign the discount codes to specific items.<p>

Dates must appear as: <font face="Courier New, Courier">YYYY-MM-DD</font><br>
Times must appear as: <font face="Courier New, Courier">HH:MM:SS</font>
<p>
</blockquote>
<center><input type=reset value="     Reset     "> &nbsp;&nbsp; <input type=submit value="Update Codes"></center>
<br>
</font></td>
</tr>

<tr>
<td align=center><?php echo FONT1 ?>
<b>Delete</b>
</td>
<td align=center><?php echo FONT1 ?>
<b>Description</b>
</td>
<td align=center width=50%><?php echo FONT1 ?>
<b>Start Time</b>
</td>
<td align=center width=50%><?php echo FONT1 ?>
<b>End Time</b>
</td>
<td align=center><?php echo FONT1 ?>
<b>Based On</b>
</td>
<td align=center><?php echo FONT1 ?>
<b>Scale Code</b>
</td>
</tr>

<?php
  for ($a = 0; $a < count($discountcodes); $a++) {
    $start_date = date("Y-m-d", $discountcodes[$a]->start_time);
    $start_time = date("H:i:s", $discountcodes[$a]->start_time);
    $end_date = date("Y-m-d", $discountcodes[$a]->end_time);
    $end_time = date("H:i:s", $discountcodes[$a]->end_time);

    printf("<tr><td align=center valign=center><input type=checkbox name=\"delete[]\" value=\"%d\"></td><td align=center><input type=text name=\"%d-description\" size=10 maxlength=200 value=\"%s\"></td><td align=center><input type=text name=\"%d-start_date\" size=10 maxlength=10 value=\"%s\"><br><input type=text name=\"%d-start_time\" size=10 maxlength=8 value=\"%s\"></td><td align=center><input type=text name=\"%d-end_date\" size=10 maxlength=10 value=\"%s\"><br><input type=text name=\"%d-end_time\" size=10 maxlength=8 value=\"%s\"></td>",
      $discountcodes[$a]->id,
      $discountcodes[$a]->id, $discountcodes[$a]->description,
      $discountcodes[$a]->id, $start_date,
      $discountcodes[$a]->id, $start_time,
      $discountcodes[$a]->id, $end_date,
      $discountcodes[$a]->id, $end_time);

    printf("<td><select name=\"%d-units\">", $discountcodes[$a]->id);
    for ($b = 0; $b < count($SALE_UNIT_TYPES); $b++) {
      $unit_type = $SALE_UNIT_TYPES[$b];
      printf("<option value=\"%d\"%s>%s", $unit_type[0],
             ($discountcodes[$a]->units == $unit_type[0] ? " selected" : ""),
             $unit_type[1]);
    }
    printf("</select></td>");

    printf("<td><select name=\"%d-code_id\">", $discountcodes[$a]->id);
    for ($b = 0; $b < count($scalecodes); $b++) {
      printf("<option value=\"%d\"%s>%s", $scalecodes[$b]->id,
             ($discountcodes[$a]->code_id == $scalecodes[$b]->id ? " selected" : ""),
             $scalecodes[$b]->description);
    }
    printf("</select></td></tr>\n");
  }
?>

<tr>
<td align=center valign=center><?php echo FONT1 ?>New<br>Code</font></td>
<td align=center>
<input type=text name="new_description" size=10 maxlength=200>
</td>
<td align=center>
<input type=text name="new_start_date" value="<?php echo $new_start_date ?>" size=10 maxlength=10><br>
<input type=text name="new_start_time" value="<?php echo $new_start_time ?>" size=10 maxlength=8>
</td>
<td align=center>
<input type=text name="new_end_date" value="<?php echo $new_end_date ?>" size=10 maxlength=10><br>
<input type=text name="new_end_time" value="<?php echo $new_end_time ?>" size=10 maxlength=8>
</td>
<td align=center>
<select name="new_units">
<?php
  for ($b = 0; $b < count($SALE_UNIT_TYPES); $b++) {
    $unit_type = $SALE_UNIT_TYPES[$b];
    printf("<option value=\"%d\">%s", $unit_type[0], $unit_type[1]);
  }
?>
</select>
</td>
<td align=center>
<select name="new_code_id">
<?php
  for ($b = 0; $b < count($scalecodes); $b++) {
    printf("<option value=\"%d\">%s", 
            $scalecodes[$b]->id, $scalecodes[$b]->description);
  }
?>
</select>
</td>

</tr>

</table>

</form>

<?php
  html_tail();
?>
