<?php
  // Get some configuration constants and functions
  require("../inc/global_config.inc");
  require("../inc/config.inc");
  require("../inc/classes.inc");
  require("../inc/functions.inc");
  require("../inc/html.inc");

  // Connect to the SQL server and select the database
  $sock = db_connect();
  $config = new Config();

  if ($step) {
    $query = "SELECT * FROM scale_codes
              ORDER BY id";

    if (!$sql_result = mysql_query($query, $sock)) {
      echo mysql_error();
      html_exit();
    }

    for ($a = 0; $a < mysql_num_rows($sql_result); $a++) {
      $item = new ScaleCode(mysql_fetch_row($sql_result), 0);
      
      $description_var = $item->id . "-description";

      if ($$description_var) {
        $item->description = $$description_var;
        $item->update();
      }
    }
  }

  if ($step && $delete && is_array($delete)) {
    // for each item in the delete[] array...
    for ($a = 0; $a < count($delete); $a++) {
      $scalecode = new ScaleCode(0, $delete[$a]);
      if ($scalecode->id)
        $scalecode->delete();
    }
  }

  if ($step && $new_scale_code) {
    $new_scale_code = trim($new_scale_code);
    $scalecode = new ScaleCode();
    $scalecode->description = $new_scale_code;
    $scalecode->insert();
  }

  $query = "SELECT * FROM scale_codes
            ORDER BY id";

  if (!$sql_result = mysql_query($query, $sock)) {
    echo mysql_error();
    html_exit();
  }

  for ($a = 0; $a < mysql_num_rows($sql_result); $a++)
    $scalecodes[] = new ScaleCode(mysql_fetch_row($sql_result), 0);

  html_head();
?>

<b>Scale Codes</b> |
<a href="disccodes.phtml"><font color=Green>Discount Codes</font></a> |
<a href="discassign.phtml"><font color=Green>Discount Assignments</font></a>

<hr noshade size=1>

<p>

<?php if ($errmsg) echo "<b>$errmsg</b><p>\n\n"; ?>

<form action="<?php echo $PHP_SELF ?>" method="post">
<input type=hidden name="step" value="1">

<table border=2 cellpadding=4 cellspacing=0 width=450>
<tr>
<td colspan=2><?php echo FONT1 ?>
<br>
<blockquote>
Create scale codes for each of the discounts you wish to offer your customers. After creating all of your scale codes, create ranges for the codes. Finally, create discount codes and assign these codes to the products you wish to put on sale.
<p>
</blockquote>
<center><input type=reset value="     Reset     "> &nbsp;&nbsp; <input type=submit value="Update Codes"></center>
<br>
</font></td>
</tr>
<tr>
<td align=center width=0><?php echo FONT1 ?>
<b>Delete</b>
</td>
<td align=center><?php echo FONT1 ?>
<b>Scale Code</b>
</td>
</tr>

<?php
  for ($a = 0; $a < count($scalecodes); $a++) {
    printf("<tr><td align=center valign=center width=0><input type=checkbox name=\"delete[]\" value=\"%d\"></td><td align=center><input type=text name=\"%d-description\" size=30 maxlength=200 value=\"%s\"> &nbsp;&nbsp; %s<a href=\"scaleranges.phtml?id=%d\">Edit Ranges</a></font></td></tr>\n",
      $scalecodes[$a]->id, $scalecodes[$a]->id, $scalecodes[$a]->description,
      FONT1, $scalecodes[$a]->id);
  }
?>

<tr>
<td>&nbsp;</td>
<td align=center>
<?php echo FONT1 ?>New code</font><br>
<input type=text name="new_scale_code" size=40 maxlength=200>
</td>
</tr>

</table>

</form>

<p>

<?php
  html_tail();
?>
