<?php
  // Get some configuration constants and functions
  require("../inc/global_config.inc");
  require("../inc/config.inc");
  require("../inc/classes.inc");
  require("../inc/functions.inc");
  require("../inc/html.inc");

  // Connect to the SQL server and select the database
  $sock = db_connect();
  $config = new Config();

  if ($step) {
    $query = "SELECT * FROM shipping_types
              ORDER BY id";

    if (!$sql_result = mysql_query($query, $sock)) {
      echo mysql_error();
      html_exit();
    }

    for ($a = 0; $a < mysql_num_rows($sql_result); $a++) {
      $item = new ShippingType(mysql_fetch_row($sql_result), 0);
      
      $description_var = $item->id . "-description";

      if ($$description_var) {
        $item->description = $$description_var;
        $item->update();
      }
    }
  }

  if ($step && $delete && is_array($delete)) {
    // for each item in the delete[] array...
    for ($a = 0; $a < count($delete); $a++) {
      $shiptype = new ShippingType(0, $delete[$a]);
      if ($shiptype->id)
        $shiptype->delete();
    }
  }

  if ($step && $new_ship_type) {
    $new_ship_type = trim($new_ship_type);
    $shiptype = new ShippingType();
    $shiptype->description = $new_ship_type;
    $shiptype->insert();
  }

  $query = "SELECT * FROM shipping_types
            ORDER BY id";

  if (!$sql_result = mysql_query($query, $sock)) {
    echo mysql_error();
    html_exit();
  }

  for ($a = 0; $a < mysql_num_rows($sql_result); $a++)
    $shiptypes[] = new ShippingType(mysql_fetch_row($sql_result), 0);

  html_head();
?>

<b>Shipping Types</b> |
<a href="shipzones.phtml"><font color=Green>Shipping Zones</font></a> |
<a href="modshiplocs.phtml"><font color=Green>Zone Assignments</font></a>

<hr noshade size=1>

<p>

<?php if ($errmsg) echo "<b>$errmsg</b><p>\n\n"; ?>

<form action="<?php echo $PHP_SELF ?>" method="post">
<input type=hidden name="step" value="1">

<table border=2 cellpadding=4 cellspacing=0 width=450>
<tr>
<td colspan=2><?php echo FONT1 ?>
<br>
<blockquote>
Create shipping types for each of the methods of shipment you wish to offer your customers. After creating all of your shipping types, assign these types to the shipping zones you create.
<p>
</blockquote>
<center><input type=reset value="     Reset     "> &nbsp;&nbsp; <input type=submit value="Update Types"></center>
<br>
</font></td>
</tr>
<tr>
<td align=center width=0><?php echo FONT1 ?>
<b>Delete</b>
</td>
<td align=center><?php echo FONT1 ?>
<b>Shipping Type</b>
</td>
</tr>

<?php
  for ($a = 0; $a < count($shiptypes); $a++) {
    printf("<tr><td align=center valign=center width=0><input type=checkbox name=\"delete[]\" value=\"%d\"></td><td align=center><input type=text name=\"%d-description\" size=40 maxlength=200 value=\"%s\"></td></tr>\n",
      $shiptypes[$a]->id, $shiptypes[$a]->id, $shiptypes[$a]->description);
  }
?>

<tr>
<td>&nbsp;</td>
<td align=center>
<?php echo FONT1 ?>New Type</font><br>
<input type=text name="new_ship_type" size=40 maxlength=200>
</td>
</tr>

</table>

</form>

<p>

<?php
  html_tail();
?>
