<?php
  // Get some configuration constants and functions
  require("../inc/global_config.inc");
  require("../inc/config.inc");
  require("../inc/classes.inc");
  require("../inc/functions.inc");
  require("../inc/html.inc");

  // Connect to the SQL server and select the database
  $sock = db_connect();
  $config = new Config();

  $now = time();

  if (!$sm) $sm = date("m");
  if (!$sd) $sd = date("d", $now - (86400 * date("w")));
  if (!$sy) $sy = date("Y");

  if (!$em) $em = date("m", $now + 86400);
  if (!$ed) $ed = date("d", $now + 86400);
  if (!$ey) $ey = date("Y", $now + 86400);

  html_head();
?>

<b>View Transactions</b> |
<a href="viewreceipt.phtml"><font color=Green>View Receipts</font></a>

<hr noshade size=1>

<p>

<form action="<?php echo $PHP_SELF ?>" method="get">

<table border=0>
<tr>
<td><?php echo FONT1 ?>Starting Date:</font></td>
<td><?php echo FONT1 ?><select name="sm">
<?php
  for ($i = 0; $i < count($MONTHS); $i++) {
    $month = $MONTHS[$i];
    echo "<option value=\"" . $month[0] . "\"" . ($month[0] == $sm ? " selected" : "") . ">" . $month[1];
  }
?>
</select></font></td>
<td><?php echo FONT1 ?><select name="sd">
<?php
  for ($i = 1; $i <= 31; $i++) {
    $day = sprintf("%02d", $i);
    echo "<option value=\"" . $day . "\"" . ($day == $sd ? " selected" : "") . ">" . $day;
  }
?>
</select></font></td>
<td><?php echo FONT1 ?><select name="sy">
<?php
  for ($i = 0; $i <= count($YEARS); $i++) {
    $year = $YEARS[$i];
    echo "<option value=\"" . $year[1] . "\"" . ($year[1] == $sy ? " selected" : "") . ">" . $year[1];
  }
?>
</select></font></td>
</tr>
<tr>
<td><?php echo FONT1 ?>Ending Date:</font></td>
<td><?php echo FONT1 ?><select name="em">
<?php
  for ($i = 0; $i < count($MONTHS); $i++) {
    $month = $MONTHS[$i];
    echo "<option value=\"" . $month[0] . "\"" . ($month[0] == $em ? " selected" : "") . ">" . $month[1];
  }
?>
</select></font></td>
<td><?php echo FONT1 ?><select name="ed">
<?php
  for ($i = 1; $i <= 31; $i++) {
    $day = sprintf("%02d", $i);
    echo "<option value=\"" . $day . "\"" . ($day == $ed ? " selected" : "") . ">" . $day;
  }
?>
</select></font></td>
<td><?php echo FONT1 ?><select name="ey">
<?php
  for ($i = 0; $i <= count($YEARS); $i++) {
    $year = $YEARS[$i];
    echo "<option value=\"" . $year[1] . "\"" . ($year[1] == $ey ? " selected" : "") . ">" . $year[1];
  }
?>
</select></font></td>
</tr>
<tr><td> </td></tr>
<tr>
<td> </td>
<td colspan=3><?php echo FONT1 ?><input type=submit value="Show Transactions"></font></td>
</tr>
</table>

</form>

<p>

<?php
  $query = "SELECT COUNT(*) FROM transactions";

  if (!$sql_result = mysql_query($query, $sock)) {
    echo mysql_error();
    html_exit();
  }

  $sql_result_row = mysql_fetch_row($sql_result);
  $total_trans = $sql_result_row[0];

  $query = "SELECT id FROM transactions
            WHERE timestamp BETWEEN " . mktime(0,0,0,$sm,$sd,$sy) . "
                                AND " . mktime(0,0,0,$em,$ed,$ey) . "
            ORDER BY timestamp";

  if (!$sql_result = mysql_query($query, $sock)) {
    echo mysql_error();
    html_exit();
  }

  $selected_trans = mysql_num_rows($sql_result);
?>

Displaying <?php echo $selected_trans ?> of <?php echo $total_trans ?> total transactions.<p>

<table border=1 cellpadding=2 cellspacing=1 width=80%>
<tr>

<td align=center><font face="Arial, MS Sans Serif, Helvetica" size=-1><b>#</b></font></td>
<td align=center><font face="Arial, MS Sans Serif, Helvetica" size=-1><b>Date</b></font></td>
<td align=center><font face="Arial, MS Sans Serif, Helvetica" size=-1><b>Order #</b></font></td>
<td align=center><font face="Arial, MS Sans Serif, Helvetica" size=-1><b>Auth. #</b></font></td>
<td align=center><font face="Arial, MS Sans Serif, Helvetica" size=-1><b>Primary Display</b></font></td>
<td align=center><font face="Arial, MS Sans Serif, Helvetica" size=-1><b>Result Code</b></font></td></tr>

<?php
  for ($i = 0; $i < mysql_num_rows($sql_result); $i++) {
    $sql_result_row = mysql_fetch_row($sql_result);
    $transaction = new Transaction(0, $sql_result_row[0]);

    $url1 = ($transaction->authno && $transaction->result == "0000" ? "<a href=\"viewreceipt.phtml?id=" . $transaction->refno . "\">" : "");
    $url2 = ($url1 ? "</a>" : "");


    printf("<tr><td><font size=-1>%d</font></td><td><font size=-1>%s</font></td><td><font size=-1>%s%s%s</font></td><td><font size=-1>%s</font></td><td><font size=-1>%s</font></td><td><font size=-1>%s</font></td></tr>\n",
      $transaction->id,
      date("M d Y H:i:s", stripslashes($transaction->timestamp)),
      $url1, stripslashes($transaction->refno), $url2,
      stripslashes($transaction->authno),
      stripslashes($transaction->pridisplay),
      stripslashes($transaction->result));
  }
?>
</table>

<?php
  html_tail();
?>
